// Copyright 2026 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package reflectdata

import (
	"cmd/compile/internal/base"
	"cmd/compile/internal/ir"
	"cmd/compile/internal/typecheck"
	"cmd/compile/internal/types"
)

// Per-(K,V) map operation generators for GOARCH=wasm3.
//
// The wasm3 backend stores maps as $go.map.<K,V> WasmGC structs
// (collectMapStruct in cmd/compile/internal/wasm3/wasmtype.go); these
// generators emit one *ir.Func per (K,V) per operation, modelled on
// hashFuncWasm3 / eqFuncWasm3 in alg.go. The body uses Go-level
// operations on a `unsafe.Pointer`-typed map argument and calls the
// runtime stubs wasm3MapUsed / wasm3MapKeys / wasm3MapValues etc.,
// which are intrinsified at SSA time to the corresponding OpWasm3Map*
// field-access ops carrying the map's *types.Type from a side channel
// (Wasm3MapHelperTypes). See cmd/compile/internal/ssagen/intrinsics.go.

// callMapHelper builds a call expression to a runtime wasm3Map* stub
// for the map type t and pins t in Wasm3MapHelperTypes so the SSA
// intrinsic can recover it. retTypes are passed to LookupRuntime for
// `any` substitution (used by Keys/Values stubs whose return is
// declared as []any but should be []K / []V per call).
func callMapHelper(t *types.Type, name string, args []ir.Node, retTypes ...*types.Type) *ir.CallExpr {
	fn := typecheck.LookupRuntime(name, retTypes...)
	call := ir.NewCallExpr(base.Pos, ir.OCALL, fn, args)
	ir.Wasm3MapHelperTypes.Store(call, t)
	return call
}

// MapDeleteFuncWasm3 is the exported entry — walkDelete on wasm3 calls
// this and emits a call to fn.Nname instead of the runtime mapdelete
// helpers.
func MapDeleteFuncWasm3(t *types.Type) *ir.Func {
	return mapDeleteFuncWasm3(t)
}

// MapAssignFuncWasm3 is the exported entry for the m[k] = v assign
// path. walkIndexMap on wasm3 with n.Assigned dispatches here.
func MapAssignFuncWasm3(t *types.Type) *ir.Func {
	return mapAssignFuncWasm3(t)
}

// MapAssignFullFuncWasm3 is the void variant for the wasm3
// walkAssign hook — takes (m, k, v) and stores v at m[k]. Avoids
// the *V return that the pointer-form path needs, since wasm3's
// interior-pointer codegen for slice elements isn't writable across
// the function boundary.
func MapAssignFullFuncWasm3(t *types.Type) *ir.Func {
	return mapAssignFullFuncWasm3(t)
}

func mapAssignFullFuncWasm3(t *types.Type) *ir.Func {
	if !t.IsMap() {
		base.Fatalf("mapAssignFullFuncWasm3: not a map type: %v", t)
	}
	sym := types.TypeSymLookup(".mapassignfull.w3." + t.LinkString())
	if sym.Def != nil {
		return sym.Def.(*ir.Name).Func
	}
	pos := base.AutogeneratedPos
	base.Pos = pos
	K := t.Key()
	V := t.Elem()
	fn := ir.NewFunc(pos, pos, sym, types.NewSignature(nil,
		[]*types.Field{
			types.NewField(pos, typecheck.Lookup("m"), types.Types[types.TUNSAFEPTR]),
			types.NewField(pos, typecheck.Lookup("key"), K),
			types.NewField(pos, typecheck.Lookup("v"), V),
		},
		nil,
	))
	sym.Def = fn.Nname
	fn.Pragma |= ir.Noinline
	typecheck.DeclFunc(fn)
	nm := fn.Dcl[0]
	nkey := fn.Dcl[1]
	nv := fn.Dcl[2]

	uintptrT := types.Types[types.TUINTPTR]
	usedVar := typecheck.TempAt(pos, ir.CurFunc, uintptrT)
	fn.Body.Append(ir.NewAssignStmt(pos, usedVar,
		callMapHelper(t, "wasm3MapUsed", []ir.Node{nm})))

	// Refresh-in-place loop (same as mapAssign body).
	gtZero := ir.NewBinaryExpr(pos, ir.OGT, usedVar, ir.NewInt(pos, 0))
	refreshKeysVar := typecheck.TempAt(pos, ir.CurFunc, types.NewSlice(K))
	refreshIVar := typecheck.TempAt(pos, ir.CurFunc, uintptrT)
	refreshValsVar := typecheck.TempAt(pos, ir.CurFunc, types.NewSlice(V))
	refreshBody := []ir.Node{
		ir.NewAssignStmt(pos, refreshKeysVar,
			callMapHelper(t, "wasm3MapKeys", []ir.Node{nm}, K)),
		ir.NewForStmt(pos,
			ir.NewAssignStmt(pos, refreshIVar, ir.NewInt(pos, 0)),
			ir.NewBinaryExpr(pos, ir.OLT, refreshIVar, usedVar),
			ir.NewAssignStmt(pos, refreshIVar, ir.NewBinaryExpr(pos, ir.OADD, refreshIVar, ir.NewInt(pos, 1))),
			[]ir.Node{
				ir.NewIfStmt(pos,
					ir.NewBinaryExpr(pos, ir.OEQ, ir.NewIndexExpr(pos, refreshKeysVar, refreshIVar), nkey),
					[]ir.Node{
						ir.NewAssignStmt(pos, refreshValsVar,
							callMapHelper(t, "wasm3MapValues", []ir.Node{nm}, V)),
						// values[i] = v; return
						ir.NewAssignStmt(pos,
							ir.NewIndexExpr(pos, refreshValsVar, refreshIVar), nv),
						ir.NewReturnStmt(pos, nil),
					}, nil),
			}, false),
	}
	fn.Body.Append(ir.NewIfStmt(pos, gtZero, refreshBody, nil))

	// Miss path: grow if used == cap, then insert.
	capVar := typecheck.TempAt(pos, ir.CurFunc, uintptrT)
	fn.Body.Append(ir.NewAssignStmt(pos, capVar,
		callMapHelper(t, "wasm3MapCap", []ir.Node{nm})))

	atCap := ir.NewBinaryExpr(pos, ir.OEQ, usedVar, capVar)
	newCapVar := typecheck.TempAt(pos, ir.CurFunc, uintptrT)
	growBody := []ir.Node{
		ir.NewAssignStmt(pos, newCapVar,
			ir.NewBinaryExpr(pos, ir.OMUL, capVar, ir.NewInt(pos, 2))),
		ir.NewIfStmt(pos,
			ir.NewBinaryExpr(pos, ir.OEQ, newCapVar, ir.NewInt(pos, 0)),
			[]ir.Node{ir.NewAssignStmt(pos, newCapVar, ir.NewInt(pos, 4))}, nil),
	}
	newKeysVar := typecheck.TempAt(pos, ir.CurFunc, types.NewSlice(K))
	newValsVar := typecheck.TempAt(pos, ir.CurFunc, types.NewSlice(V))
	makeKeys := ir.NewMakeExpr(pos, ir.OMAKESLICE, newCapVar, newCapVar)
	makeKeys.SetType(types.NewSlice(K))
	makeKeys.SetTypecheck(1)
	makeVals := ir.NewMakeExpr(pos, ir.OMAKESLICE, newCapVar, newCapVar)
	makeVals.SetType(types.NewSlice(V))
	makeVals.SetTypecheck(1)
	growBody = append(growBody,
		ir.NewAssignStmt(pos, newKeysVar, makeKeys),
		ir.NewAssignStmt(pos, newValsVar, makeVals))
	oldKeysVar := typecheck.TempAt(pos, ir.CurFunc, types.NewSlice(K))
	oldValsVar := typecheck.TempAt(pos, ir.CurFunc, types.NewSlice(V))
	copyIVar := typecheck.TempAt(pos, ir.CurFunc, uintptrT)
	copyBody := []ir.Node{
		ir.NewAssignStmt(pos, oldKeysVar,
			callMapHelper(t, "wasm3MapKeys", []ir.Node{nm}, K)),
		ir.NewAssignStmt(pos, oldValsVar,
			callMapHelper(t, "wasm3MapValues", []ir.Node{nm}, V)),
		ir.NewForStmt(pos,
			ir.NewAssignStmt(pos, copyIVar, ir.NewInt(pos, 0)),
			ir.NewBinaryExpr(pos, ir.OLT, copyIVar, usedVar),
			ir.NewAssignStmt(pos, copyIVar, ir.NewBinaryExpr(pos, ir.OADD, copyIVar, ir.NewInt(pos, 1))),
			[]ir.Node{
				ir.NewAssignStmt(pos,
					ir.NewIndexExpr(pos, newKeysVar, copyIVar),
					ir.NewIndexExpr(pos, oldKeysVar, copyIVar)),
				ir.NewAssignStmt(pos,
					ir.NewIndexExpr(pos, newValsVar, copyIVar),
					ir.NewIndexExpr(pos, oldValsVar, copyIVar)),
			}, false),
	}
	growBody = append(growBody,
		ir.NewIfStmt(pos,
			ir.NewBinaryExpr(pos, ir.OGT, capVar, ir.NewInt(pos, 0)),
			copyBody, nil))
	growBody = append(growBody,
		callMapHelper(t, "wasm3MapKeysSet", []ir.Node{nm, newKeysVar}, K),
		callMapHelper(t, "wasm3MapValuesSet", []ir.Node{nm, newValsVar}, V),
		callMapHelper(t, "wasm3MapCapSet", []ir.Node{nm, newCapVar}))
	fn.Body.Append(ir.NewIfStmt(pos, atCap, growBody, nil))

	// Insert: keys[used] = key; values[used] = v; used++
	insertKeysVar := typecheck.TempAt(pos, ir.CurFunc, types.NewSlice(K))
	fn.Body.Append(ir.NewAssignStmt(pos, insertKeysVar,
		callMapHelper(t, "wasm3MapKeys", []ir.Node{nm}, K)))
	fn.Body.Append(ir.NewAssignStmt(pos,
		ir.NewIndexExpr(pos, insertKeysVar, usedVar), nkey))
	insertValsVar := typecheck.TempAt(pos, ir.CurFunc, types.NewSlice(V))
	fn.Body.Append(ir.NewAssignStmt(pos, insertValsVar,
		callMapHelper(t, "wasm3MapValues", []ir.Node{nm}, V)))
	fn.Body.Append(ir.NewAssignStmt(pos,
		ir.NewIndexExpr(pos, insertValsVar, usedVar), nv))
	fn.Body.Append(callMapHelper(t, "wasm3MapUsedSet", []ir.Node{nm,
		ir.NewBinaryExpr(pos, ir.OADD, usedVar, ir.NewInt(pos, 1))}))

	typecheck.FinishFuncBody()
	ir.WithFunc(fn, func() { typecheck.Stmts(fn.Body) })
	return fn
}

// mapAssignFuncWasm3 builds the per-(K,V) assign function for t.
// On refresh-in-place: returns &values[i]. On miss: grow if used == cap
// (double cap, min 8, allocate fresh make([]K) / make([]V), copy old,
// store back via the *Set helpers), then write key at index used,
// increment used, return pointer to the (zero-initialized) value slot.
// The caller writes the actual value through the returned *V.
func mapAssignFuncWasm3(t *types.Type) *ir.Func {
	if !t.IsMap() {
		base.Fatalf("mapAssignFuncWasm3: not a map type: %v", t)
	}
	sym := types.TypeSymLookup(".mapassign.w3." + t.LinkString())
	if sym.Def != nil {
		return sym.Def.(*ir.Name).Func
	}
	pos := base.AutogeneratedPos
	base.Pos = pos
	K := t.Key()
	V := t.Elem()
	ptrV := types.NewPtr(V)
	fn := ir.NewFunc(pos, pos, sym, types.NewSignature(nil,
		[]*types.Field{
			types.NewField(pos, typecheck.Lookup("m"), types.Types[types.TUNSAFEPTR]),
			types.NewField(pos, typecheck.Lookup("key"), K),
		},
		[]*types.Field{
			types.NewField(pos, nil, ptrV),
		},
	))
	sym.Def = fn.Nname
	fn.Pragma |= ir.Noinline
	typecheck.DeclFunc(fn)
	nm := fn.Dcl[0]
	nkey := fn.Dcl[1]
	uintptrT := types.Types[types.TUINTPTR]

	// used := wasm3MapUsed(m)
	usedVar := typecheck.TempAt(pos, ir.CurFunc, uintptrT)
	fn.Body.Append(ir.NewAssignStmt(pos, usedVar,
		callMapHelper(t, "wasm3MapUsed", []ir.Node{nm})))

	// Refresh-in-place: if used > 0 { keys := wasm3MapKeys(m); for i := 0; i < used; i++ { if keys[i] == key { vs := wasm3MapValues(m); return &vs[i] } } }
	gtZero := ir.NewBinaryExpr(pos, ir.OGT, usedVar, ir.NewInt(pos, 0))
	refreshKeysVar := typecheck.TempAt(pos, ir.CurFunc, types.NewSlice(K))
	refreshIVar := typecheck.TempAt(pos, ir.CurFunc, uintptrT)
	refreshValsVar := typecheck.TempAt(pos, ir.CurFunc, types.NewSlice(V))
	refreshBody := []ir.Node{
		ir.NewAssignStmt(pos, refreshKeysVar,
			callMapHelper(t, "wasm3MapKeys", []ir.Node{nm}, K)),
		ir.NewForStmt(pos,
			ir.NewAssignStmt(pos, refreshIVar, ir.NewInt(pos, 0)),
			ir.NewBinaryExpr(pos, ir.OLT, refreshIVar, usedVar),
			ir.NewAssignStmt(pos, refreshIVar, ir.NewBinaryExpr(pos, ir.OADD, refreshIVar, ir.NewInt(pos, 1))),
			[]ir.Node{
				ir.NewIfStmt(pos,
					ir.NewBinaryExpr(pos, ir.OEQ, ir.NewIndexExpr(pos, refreshKeysVar, refreshIVar), nkey),
					[]ir.Node{
						ir.NewAssignStmt(pos, refreshValsVar,
							callMapHelper(t, "wasm3MapValues", []ir.Node{nm}, V)),
						ir.NewReturnStmt(pos, []ir.Node{
							typecheck.NodAddr(ir.NewIndexExpr(pos, refreshValsVar, refreshIVar)),
						}),
					}, nil),
			}, false),
	}
	fn.Body.Append(ir.NewIfStmt(pos, gtZero, refreshBody, nil))

	// Miss: cap := wasm3MapCap(m); if used == cap { grow ... }
	capVar := typecheck.TempAt(pos, ir.CurFunc, uintptrT)
	fn.Body.Append(ir.NewAssignStmt(pos, capVar,
		callMapHelper(t, "wasm3MapCap", []ir.Node{nm})))

	atCap := ir.NewBinaryExpr(pos, ir.OEQ, usedVar, capVar)
	newCapVar := typecheck.TempAt(pos, ir.CurFunc, uintptrT)
	growBody := []ir.Node{
		// newCap := cap * 2; if newCap == 0 { newCap = 4 }
		ir.NewAssignStmt(pos, newCapVar,
			ir.NewBinaryExpr(pos, ir.OMUL, capVar, ir.NewInt(pos, 2))),
		ir.NewIfStmt(pos,
			ir.NewBinaryExpr(pos, ir.OEQ, newCapVar, ir.NewInt(pos, 0)),
			[]ir.Node{ir.NewAssignStmt(pos, newCapVar, ir.NewInt(pos, 4))}, nil),
	}
	// newKeys := make([]K, newCap); newValues := make([]V, newCap)
	newKeysVar := typecheck.TempAt(pos, ir.CurFunc, types.NewSlice(K))
	newValsVar := typecheck.TempAt(pos, ir.CurFunc, types.NewSlice(V))
	makeKeys := ir.NewMakeExpr(pos, ir.OMAKESLICE, newCapVar, newCapVar)
	makeKeys.SetType(types.NewSlice(K))
	makeKeys.SetTypecheck(1)
	makeVals := ir.NewMakeExpr(pos, ir.OMAKESLICE, newCapVar, newCapVar)
	makeVals.SetType(types.NewSlice(V))
	makeVals.SetTypecheck(1)
	growBody = append(growBody,
		ir.NewAssignStmt(pos, newKeysVar, makeKeys),
		ir.NewAssignStmt(pos, newValsVar, makeVals))
	// if cap > 0 { copy old data }
	oldKeysVar := typecheck.TempAt(pos, ir.CurFunc, types.NewSlice(K))
	oldValsVar := typecheck.TempAt(pos, ir.CurFunc, types.NewSlice(V))
	copyIVar := typecheck.TempAt(pos, ir.CurFunc, uintptrT)
	copyBody := []ir.Node{
		ir.NewAssignStmt(pos, oldKeysVar,
			callMapHelper(t, "wasm3MapKeys", []ir.Node{nm}, K)),
		ir.NewAssignStmt(pos, oldValsVar,
			callMapHelper(t, "wasm3MapValues", []ir.Node{nm}, V)),
		ir.NewForStmt(pos,
			ir.NewAssignStmt(pos, copyIVar, ir.NewInt(pos, 0)),
			ir.NewBinaryExpr(pos, ir.OLT, copyIVar, usedVar),
			ir.NewAssignStmt(pos, copyIVar, ir.NewBinaryExpr(pos, ir.OADD, copyIVar, ir.NewInt(pos, 1))),
			[]ir.Node{
				ir.NewAssignStmt(pos,
					ir.NewIndexExpr(pos, newKeysVar, copyIVar),
					ir.NewIndexExpr(pos, oldKeysVar, copyIVar)),
				ir.NewAssignStmt(pos,
					ir.NewIndexExpr(pos, newValsVar, copyIVar),
					ir.NewIndexExpr(pos, oldValsVar, copyIVar)),
			}, false),
	}
	growBody = append(growBody,
		ir.NewIfStmt(pos,
			ir.NewBinaryExpr(pos, ir.OGT, capVar, ir.NewInt(pos, 0)),
			copyBody, nil))
	// Writeback: wasm3MapKeysSet(m, newKeys); wasm3MapValuesSet(m, newValues); wasm3MapCapSet(m, newCap)
	// The any in wasm3MapKeysSet/ValuesSet stub signatures is the slice
	// element type — substitute with K / V via the LookupRuntime variadic.
	growBody = append(growBody,
		callMapHelper(t, "wasm3MapKeysSet", []ir.Node{nm, newKeysVar}, K),
		callMapHelper(t, "wasm3MapValuesSet", []ir.Node{nm, newValsVar}, V),
		callMapHelper(t, "wasm3MapCapSet", []ir.Node{nm, newCapVar}))
	fn.Body.Append(ir.NewIfStmt(pos, atCap, growBody, nil))

	// Insert: keys := wasm3MapKeys(m); keys[used] = key; wasm3MapUsedSet(m, used+1); vs := wasm3MapValues(m); return &vs[used]
	insertKeysVar := typecheck.TempAt(pos, ir.CurFunc, types.NewSlice(K))
	fn.Body.Append(ir.NewAssignStmt(pos, insertKeysVar,
		callMapHelper(t, "wasm3MapKeys", []ir.Node{nm}, K)))
	fn.Body.Append(ir.NewAssignStmt(pos,
		ir.NewIndexExpr(pos, insertKeysVar, usedVar), nkey))
	fn.Body.Append(callMapHelper(t, "wasm3MapUsedSet", []ir.Node{nm,
		ir.NewBinaryExpr(pos, ir.OADD, usedVar, ir.NewInt(pos, 1))}))
	insertValsVar := typecheck.TempAt(pos, ir.CurFunc, types.NewSlice(V))
	fn.Body.Append(ir.NewAssignStmt(pos, insertValsVar,
		callMapHelper(t, "wasm3MapValues", []ir.Node{nm}, V)))
	fn.Body.Append(ir.NewReturnStmt(pos, []ir.Node{
		typecheck.NodAddr(ir.NewIndexExpr(pos, insertValsVar, usedVar)),
	}))

	typecheck.FinishFuncBody()
	ir.WithFunc(fn, func() { typecheck.Stmts(fn.Body) })
	return fn
}

// MapAccess2FuncWasm3 is the exported entry for the v,ok := m[k]
// read path. Same shape as MapAccessFuncWasm3 but returns (*V, bool).
func MapAccess2FuncWasm3(t *types.Type) *ir.Func {
	return mapAccess2FuncWasm3(t)
}

func mapAccess2FuncWasm3(t *types.Type) *ir.Func {
	if !t.IsMap() {
		base.Fatalf("mapAccess2FuncWasm3: not a map type: %v", t)
	}
	sym := types.TypeSymLookup(".mapacc2.w3." + t.LinkString())
	if sym.Def != nil {
		return sym.Def.(*ir.Name).Func
	}
	pos := base.AutogeneratedPos
	base.Pos = pos
	K := t.Key()
	V := t.Elem()
	ptrV := types.NewPtr(V)
	fn := ir.NewFunc(pos, pos, sym, types.NewSignature(nil,
		[]*types.Field{
			types.NewField(pos, typecheck.Lookup("m"), types.Types[types.TUNSAFEPTR]),
			types.NewField(pos, typecheck.Lookup("key"), K),
		},
		[]*types.Field{
			types.NewField(pos, nil, ptrV),
			types.NewField(pos, nil, types.Types[types.TBOOL]),
		},
	))
	sym.Def = fn.Nname
	fn.Pragma |= ir.Noinline
	typecheck.DeclFunc(fn)
	nm := fn.Dcl[0]
	nkey := fn.Dcl[1]
	uintptrT := types.Types[types.TUINTPTR]
	usedVar := typecheck.TempAt(pos, ir.CurFunc, uintptrT)
	fn.Body.Append(ir.NewAssignStmt(pos, usedVar,
		callMapHelper(t, "wasm3MapUsed", []ir.Node{nm})))
	gtZero := ir.NewBinaryExpr(pos, ir.OGT, usedVar, ir.NewInt(pos, 0))
	seekBody := []ir.Node{}
	keysVar := typecheck.TempAt(pos, ir.CurFunc, types.NewSlice(K))
	seekBody = append(seekBody, ir.NewAssignStmt(pos, keysVar,
		callMapHelper(t, "wasm3MapKeys", []ir.Node{nm}, K)))
	iVar := typecheck.TempAt(pos, ir.CurFunc, uintptrT)
	initFor := ir.NewAssignStmt(pos, iVar, ir.NewInt(pos, 0))
	condFor := ir.NewBinaryExpr(pos, ir.OLT, iVar, usedVar)
	postFor := ir.NewAssignStmt(pos, iVar, ir.NewBinaryExpr(pos, ir.OADD, iVar, ir.NewInt(pos, 1)))
	matchCond := ir.NewBinaryExpr(pos, ir.OEQ, ir.NewIndexExpr(pos, keysVar, iVar), nkey)
	valsVar := typecheck.TempAt(pos, ir.CurFunc, types.NewSlice(V))
	matchBody := []ir.Node{
		ir.NewAssignStmt(pos, valsVar,
			callMapHelper(t, "wasm3MapValues", []ir.Node{nm}, V)),
		ir.NewReturnStmt(pos, []ir.Node{
			typecheck.NodAddr(ir.NewIndexExpr(pos, valsVar, iVar)),
			ir.NewBool(pos, true),
		}),
	}
	matchIf := ir.NewIfStmt(pos, matchCond, matchBody, nil)
	seekBody = append(seekBody, ir.NewForStmt(pos, initFor, condFor, postFor, []ir.Node{matchIf}, false))
	fn.Body.Append(ir.NewIfStmt(pos, gtZero, seekBody, nil))
	fn.Body.Append(ir.NewReturnStmt(pos, []ir.Node{
		ir.NewUnaryExpr(pos, ir.ONEW, ir.TypeNode(V)),
		ir.NewBool(pos, false),
	}))
	typecheck.FinishFuncBody()
	ir.WithFunc(fn, func() { typecheck.Stmts(fn.Body) })
	return fn
}

// MapAccessFuncWasm3 is the exported entry for the m[k] read path.
// walkIndexMap on wasm3 calls this and emits a call to fn.Nname
// instead of the runtime mapaccess_* helpers. The returned *V is
// dereferenced by the caller.
func MapAccessFuncWasm3(t *types.Type) *ir.Func {
	return mapAccessFuncWasm3(t)
}

// mapAccessFuncWasm3 builds the per-(K,V) access function for t. It
// linear-seeks for the key and returns &values[i] on match; on miss
// returns new(V) — a fresh zero allocated via the wasm3 typed
// allocation path (OpWasm3StructNewDefault / BoxNewDefault).
func mapAccessFuncWasm3(t *types.Type) *ir.Func {
	if !t.IsMap() {
		base.Fatalf("mapAccessFuncWasm3: not a map type: %v", t)
	}
	sym := types.TypeSymLookup(".mapacc.w3." + t.LinkString())
	if sym.Def != nil {
		return sym.Def.(*ir.Name).Func
	}

	pos := base.AutogeneratedPos
	base.Pos = pos

	K := t.Key()
	V := t.Elem()
	ptrV := types.NewPtr(V)

	// func sym(m unsafe.Pointer, key K) *V
	fn := ir.NewFunc(pos, pos, sym, types.NewSignature(nil,
		[]*types.Field{
			types.NewField(pos, typecheck.Lookup("m"), types.Types[types.TUNSAFEPTR]),
			types.NewField(pos, typecheck.Lookup("key"), K),
		},
		[]*types.Field{
			types.NewField(pos, nil, ptrV),
		},
	))
	sym.Def = fn.Nname
	fn.Pragma |= ir.Noinline
	typecheck.DeclFunc(fn)
	nm := fn.Dcl[0]
	nkey := fn.Dcl[1]

	uintptrT := types.Types[types.TUINTPTR]

	// used := wasm3MapUsed(m)
	usedVar := typecheck.TempAt(pos, ir.CurFunc, uintptrT)
	fn.Body.Append(ir.NewAssignStmt(pos, usedVar,
		callMapHelper(t, "wasm3MapUsed", []ir.Node{nm})))

	// if used > 0 { ... seek }
	gtZero := ir.NewBinaryExpr(pos, ir.OGT, usedVar, ir.NewInt(pos, 0))
	seekBody := []ir.Node{}

	// keys := wasm3MapKeys(m)
	keysVar := typecheck.TempAt(pos, ir.CurFunc, types.NewSlice(K))
	seekBody = append(seekBody, ir.NewAssignStmt(pos, keysVar,
		callMapHelper(t, "wasm3MapKeys", []ir.Node{nm}, K)))

	// for i := uintptr(0); i < used; i++ {
	//   if keys[i] == key { values := wasm3MapValues(m); return &values[i] }
	// }
	iVar := typecheck.TempAt(pos, ir.CurFunc, uintptrT)
	initFor := ir.NewAssignStmt(pos, iVar, ir.NewInt(pos, 0))
	condFor := ir.NewBinaryExpr(pos, ir.OLT, iVar, usedVar)
	postFor := ir.NewAssignStmt(pos, iVar, ir.NewBinaryExpr(pos, ir.OADD, iVar, ir.NewInt(pos, 1)))

	keysI := ir.NewIndexExpr(pos, keysVar, iVar)
	matchCond := ir.NewBinaryExpr(pos, ir.OEQ, keysI, nkey)

	valsVar := typecheck.TempAt(pos, ir.CurFunc, types.NewSlice(V))
	matchBody := []ir.Node{
		ir.NewAssignStmt(pos, valsVar,
			callMapHelper(t, "wasm3MapValues", []ir.Node{nm}, V)),
		ir.NewReturnStmt(pos, []ir.Node{
			typecheck.NodAddr(ir.NewIndexExpr(pos, valsVar, iVar)),
		}),
	}
	matchIf := ir.NewIfStmt(pos, matchCond, matchBody, nil)

	forStmt := ir.NewForStmt(pos, initFor, condFor, postFor, []ir.Node{matchIf}, false)
	seekBody = append(seekBody, forStmt)

	fn.Body.Append(ir.NewIfStmt(pos, gtZero, seekBody, nil))

	// On miss: return new(V) — wasm3 intrinsifies new() for all
	// supported V kinds via OpWasm3StructNewDefault /
	// OpWasm3ArrayNewDefault / OpWasm3BoxNewDefault. The fresh zero
	// satisfies the mapaccess1 contract (non-nil pointer, value is
	// the zero of V) at the cost of one allocation per missing-key
	// lookup. A package-level zero would avoid the alloc but needs
	// type-keyed global symbol generation; deferred.
	zeroNew := ir.NewUnaryExpr(pos, ir.ONEW, ir.TypeNode(V))
	fn.Body.Append(ir.NewReturnStmt(pos, []ir.Node{zeroNew}))

	typecheck.FinishFuncBody()
	ir.WithFunc(fn, func() { typecheck.Stmts(fn.Body) })
	return fn
}

// mapDeleteFuncWasm3 builds the per-(K,V) delete function for the Go
// map type t. The body linear-seeks for key equality, then swap-removes
// (move last entry into the deleted slot) and decrements used. The
// final slot is zeroed to release the key/value references so the host
// GC can reclaim them.
//
// The compiler-emitted call site (walkDelete on wasm3) does:
//   sym(unsafe.Pointer(m), key)
//
// after which the map is logically updated. Returns nil if t is not a
// map.
func mapDeleteFuncWasm3(t *types.Type) *ir.Func {
	if !t.IsMap() {
		base.Fatalf("mapDeleteFuncWasm3: not a map type: %v", t)
	}
	sym := types.TypeSymLookup(".mapdel.w3." + t.LinkString())
	if sym.Def != nil {
		return sym.Def.(*ir.Name).Func
	}

	pos := base.AutogeneratedPos
	base.Pos = pos

	K := t.Key()
	V := t.Elem()

	// func sym(m unsafe.Pointer, key K)
	fn := ir.NewFunc(pos, pos, sym, types.NewSignature(nil,
		[]*types.Field{
			types.NewField(pos, typecheck.Lookup("m"), types.Types[types.TUNSAFEPTR]),
			types.NewField(pos, typecheck.Lookup("key"), K),
		},
		nil,
	))
	sym.Def = fn.Nname
	fn.Pragma |= ir.Noinline
	typecheck.DeclFunc(fn)
	nm := fn.Dcl[0]   // m unsafe.Pointer
	nkey := fn.Dcl[1] // key K

	uintptrT := types.Types[types.TUINTPTR]

	// used := wasm3MapUsed(m)
	usedVar := typecheck.TempAt(pos, ir.CurFunc, uintptrT)
	usedCall := callMapHelper(t, "wasm3MapUsed", []ir.Node{nm})
	fn.Body.Append(ir.NewAssignStmt(pos, usedVar, usedCall))

	// if used == 0 { return }
	zeroUsed := ir.NewBinaryExpr(pos, ir.OEQ, usedVar, ir.NewInt(pos, 0))
	earlyReturn := ir.NewIfStmt(pos, zeroUsed, []ir.Node{ir.NewReturnStmt(pos, nil)}, nil)
	fn.Body.Append(earlyReturn)

	// keys := wasm3MapKeys(m)  // []K
	keysVar := typecheck.TempAt(pos, ir.CurFunc, types.NewSlice(K))
	keysCall := callMapHelper(t, "wasm3MapKeys", []ir.Node{nm}, K)
	fn.Body.Append(ir.NewAssignStmt(pos, keysVar, keysCall))

	// for i := uintptr(0); i < used; i++ {
	//   if keys[i] == key {
	//     last := used - 1
	//     if i != last {
	//       keys[i] = keys[last]
	//       values := wasm3MapValues(m)
	//       values[i] = values[last]
	//     }
	//     // zero tail
	//     var zk K
	//     keys[last] = zk
	//     var zv V
	//     valuesEnd := wasm3MapValues(m)
	//     valuesEnd[last] = zv
	//     wasm3MapUsedSet(m, used - 1)
	//     return
	//   }
	// }
	iVar := typecheck.TempAt(pos, ir.CurFunc, uintptrT)
	initFor := ir.NewAssignStmt(pos, iVar, ir.NewInt(pos, 0))
	condFor := ir.NewBinaryExpr(pos, ir.OLT, iVar, usedVar)
	postFor := ir.NewAssignStmt(pos, iVar, ir.NewBinaryExpr(pos, ir.OADD, iVar, ir.NewInt(pos, 1)))

	// keys[i]
	keysI := ir.NewIndexExpr(pos, keysVar, iVar)
	// keys[i] == key
	matchCond := ir.NewBinaryExpr(pos, ir.OEQ, keysI, nkey)

	matchBody := []ir.Node{}

	// last := used - 1
	lastVar := typecheck.TempAt(pos, ir.CurFunc, uintptrT)
	matchBody = append(matchBody,
		ir.NewAssignStmt(pos, lastVar, ir.NewBinaryExpr(pos, ir.OSUB, usedVar, ir.NewInt(pos, 1))))

	// if i != last { keys[i] = keys[last]; values := wasm3MapValues(m); values[i] = values[last] }
	swapCond := ir.NewBinaryExpr(pos, ir.ONE, iVar, lastVar)
	swapBody := []ir.Node{
		ir.NewAssignStmt(pos,
			ir.NewIndexExpr(pos, keysVar, iVar),
			ir.NewIndexExpr(pos, keysVar, lastVar)),
	}
	valsSwapVar := typecheck.TempAt(pos, ir.CurFunc, types.NewSlice(V))
	swapBody = append(swapBody,
		ir.NewAssignStmt(pos, valsSwapVar,
			callMapHelper(t, "wasm3MapValues", []ir.Node{nm}, V)))
	swapBody = append(swapBody,
		ir.NewAssignStmt(pos,
			ir.NewIndexExpr(pos, valsSwapVar, iVar),
			ir.NewIndexExpr(pos, valsSwapVar, lastVar)))
	matchBody = append(matchBody, ir.NewIfStmt(pos, swapCond, swapBody, nil))

	// keys[last] = zero K
	zK := typecheck.TempAt(pos, ir.CurFunc, K)
	matchBody = append(matchBody, ir.NewAssignStmt(pos, zK, nil))
	matchBody = append(matchBody,
		ir.NewAssignStmt(pos, ir.NewIndexExpr(pos, keysVar, lastVar), zK))

	// valsEnd := wasm3MapValues(m); valsEnd[last] = zero V
	valsEndVar := typecheck.TempAt(pos, ir.CurFunc, types.NewSlice(V))
	matchBody = append(matchBody,
		ir.NewAssignStmt(pos, valsEndVar,
			callMapHelper(t, "wasm3MapValues", []ir.Node{nm}, V)))
	zV := typecheck.TempAt(pos, ir.CurFunc, V)
	matchBody = append(matchBody, ir.NewAssignStmt(pos, zV, nil))
	matchBody = append(matchBody,
		ir.NewAssignStmt(pos, ir.NewIndexExpr(pos, valsEndVar, lastVar), zV))

	// wasm3MapUsedSet(m, used - 1)
	newUsed := ir.NewBinaryExpr(pos, ir.OSUB, usedVar, ir.NewInt(pos, 1))
	setCall := callMapHelper(t, "wasm3MapUsedSet", []ir.Node{nm, newUsed})
	matchBody = append(matchBody, setCall)

	// return
	matchBody = append(matchBody, ir.NewReturnStmt(pos, nil))

	matchIf := ir.NewIfStmt(pos, matchCond, matchBody, nil)
	forBody := []ir.Node{matchIf}
	forStmt := ir.NewForStmt(pos, initFor, condFor, postFor, forBody, false)
	fn.Body.Append(forStmt)

	typecheck.FinishFuncBody()
	ir.WithFunc(fn, func() { typecheck.Stmts(fn.Body) })
	return fn
}
